// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aboalkdajwkuccvedyla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib2Fsa2RhandrdWNjdmVkeWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDMyNjUsImV4cCI6MjA3NDI3OTI2NX0.y4FWc7SUI2iR3RVDW7AQSkPJhYexG2rjeBG9c1LATzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});